// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: analytics/analytics.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Analytics_GetArticlesCounts_FullMethodName            = "/analytics.Analytics/GetArticlesCounts"
	Analytics_SetArticlesAction_FullMethodName            = "/analytics.Analytics/SetArticlesAction"
	Analytics_GetArticlesByActionOnAccount_FullMethodName = "/analytics.Analytics/GetArticlesByActionOnAccount"
	Analytics_GetTrendingArticles_FullMethodName          = "/analytics.Analytics/GetTrendingArticles"
)

// AnalyticsClient is the client API for Analytics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsClient interface {
	GetArticlesCounts(ctx context.Context, in *GetArticlesCountsParams, opts ...grpc.CallOption) (*GetArticlesCountsResponse, error)
	SetArticlesAction(ctx context.Context, in *SetArticlesActionParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetArticlesByActionOnAccount(ctx context.Context, in *GetArticlesByActionOnAccountParams, opts ...grpc.CallOption) (*ArticleUuidsResponse, error)
	GetTrendingArticles(ctx context.Context, in *GetTrendingArticlesParams, opts ...grpc.CallOption) (*ArticleUuidsResponse, error)
}

type analyticsClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsClient(cc grpc.ClientConnInterface) AnalyticsClient {
	return &analyticsClient{cc}
}

func (c *analyticsClient) GetArticlesCounts(ctx context.Context, in *GetArticlesCountsParams, opts ...grpc.CallOption) (*GetArticlesCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticlesCountsResponse)
	err := c.cc.Invoke(ctx, Analytics_GetArticlesCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) SetArticlesAction(ctx context.Context, in *SetArticlesActionParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Analytics_SetArticlesAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetArticlesByActionOnAccount(ctx context.Context, in *GetArticlesByActionOnAccountParams, opts ...grpc.CallOption) (*ArticleUuidsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleUuidsResponse)
	err := c.cc.Invoke(ctx, Analytics_GetArticlesByActionOnAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetTrendingArticles(ctx context.Context, in *GetTrendingArticlesParams, opts ...grpc.CallOption) (*ArticleUuidsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleUuidsResponse)
	err := c.cc.Invoke(ctx, Analytics_GetTrendingArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServer is the server API for Analytics service.
// All implementations must embed UnimplementedAnalyticsServer
// for forward compatibility.
type AnalyticsServer interface {
	GetArticlesCounts(context.Context, *GetArticlesCountsParams) (*GetArticlesCountsResponse, error)
	SetArticlesAction(context.Context, *SetArticlesActionParams) (*emptypb.Empty, error)
	GetArticlesByActionOnAccount(context.Context, *GetArticlesByActionOnAccountParams) (*ArticleUuidsResponse, error)
	GetTrendingArticles(context.Context, *GetTrendingArticlesParams) (*ArticleUuidsResponse, error)
	mustEmbedUnimplementedAnalyticsServer()
}

// UnimplementedAnalyticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServer struct{}

func (UnimplementedAnalyticsServer) GetArticlesCounts(context.Context, *GetArticlesCountsParams) (*GetArticlesCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticlesCounts not implemented")
}
func (UnimplementedAnalyticsServer) SetArticlesAction(context.Context, *SetArticlesActionParams) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetArticlesAction not implemented")
}
func (UnimplementedAnalyticsServer) GetArticlesByActionOnAccount(context.Context, *GetArticlesByActionOnAccountParams) (*ArticleUuidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticlesByActionOnAccount not implemented")
}
func (UnimplementedAnalyticsServer) GetTrendingArticles(context.Context, *GetTrendingArticlesParams) (*ArticleUuidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendingArticles not implemented")
}
func (UnimplementedAnalyticsServer) mustEmbedUnimplementedAnalyticsServer() {}
func (UnimplementedAnalyticsServer) testEmbeddedByValue()                   {}

// UnsafeAnalyticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServer will
// result in compilation errors.
type UnsafeAnalyticsServer interface {
	mustEmbedUnimplementedAnalyticsServer()
}

func RegisterAnalyticsServer(s grpc.ServiceRegistrar, srv AnalyticsServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Analytics_ServiceDesc, srv)
}

func _Analytics_GetArticlesCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticlesCountsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetArticlesCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetArticlesCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetArticlesCounts(ctx, req.(*GetArticlesCountsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_SetArticlesAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetArticlesActionParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).SetArticlesAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_SetArticlesAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).SetArticlesAction(ctx, req.(*SetArticlesActionParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetArticlesByActionOnAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticlesByActionOnAccountParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetArticlesByActionOnAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetArticlesByActionOnAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetArticlesByActionOnAccount(ctx, req.(*GetArticlesByActionOnAccountParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetTrendingArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingArticlesParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetTrendingArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetTrendingArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetTrendingArticles(ctx, req.(*GetTrendingArticlesParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Analytics_ServiceDesc is the grpc.ServiceDesc for Analytics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analytics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.Analytics",
	HandlerType: (*AnalyticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticlesCounts",
			Handler:    _Analytics_GetArticlesCounts_Handler,
		},
		{
			MethodName: "SetArticlesAction",
			Handler:    _Analytics_SetArticlesAction_Handler,
		},
		{
			MethodName: "GetArticlesByActionOnAccount",
			Handler:    _Analytics_GetArticlesByActionOnAccount_Handler,
		},
		{
			MethodName: "GetTrendingArticles",
			Handler:    _Analytics_GetTrendingArticles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/analytics.proto",
}
