// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: analytics/news.proto

package analyticsv1

import (
	common "github.com/x3a-tech/contract-go/common"
	news "github.com/x3a-tech/contract-go/news"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArticlesCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleUuid   []byte                 `protobuf:"bytes,1,opt,name=article_uuid,json=articleUuid,proto3" json:"article_uuid,omitempty"`
	Counts        *news.ArticleCounts    `protobuf:"bytes,2,opt,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlesCounts) Reset() {
	*x = ArticlesCounts{}
	mi := &file_analytics_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlesCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlesCounts) ProtoMessage() {}

func (x *ArticlesCounts) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlesCounts.ProtoReflect.Descriptor instead.
func (*ArticlesCounts) Descriptor() ([]byte, []int) {
	return file_analytics_news_proto_rawDescGZIP(), []int{0}
}

func (x *ArticlesCounts) GetArticleUuid() []byte {
	if x != nil {
		return x.ArticleUuid
	}
	return nil
}

func (x *ArticlesCounts) GetCounts() *news.ArticleCounts {
	if x != nil {
		return x.Counts
	}
	return nil
}

type GetArticlesCountsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleUuids  [][]byte               `protobuf:"bytes,1,rep,name=article_uuids,json=articleUuids,proto3" json:"article_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesCountsParams) Reset() {
	*x = GetArticlesCountsParams{}
	mi := &file_analytics_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesCountsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesCountsParams) ProtoMessage() {}

func (x *GetArticlesCountsParams) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesCountsParams.ProtoReflect.Descriptor instead.
func (*GetArticlesCountsParams) Descriptor() ([]byte, []int) {
	return file_analytics_news_proto_rawDescGZIP(), []int{1}
}

func (x *GetArticlesCountsParams) GetArticleUuids() [][]byte {
	if x != nil {
		return x.ArticleUuids
	}
	return nil
}

type GetArticlesCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ArticlesCounts      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesCountsResponse) Reset() {
	*x = GetArticlesCountsResponse{}
	mi := &file_analytics_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesCountsResponse) ProtoMessage() {}

func (x *GetArticlesCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesCountsResponse.ProtoReflect.Descriptor instead.
func (*GetArticlesCountsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_news_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticlesCountsResponse) GetList() []*ArticlesCounts {
	if x != nil {
		return x.List
	}
	return nil
}

type ArticlesView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleUuid   []byte                 `protobuf:"bytes,1,opt,name=article_uuid,json=articleUuid,proto3" json:"article_uuid,omitempty"`
	AccountUuid   []byte                 `protobuf:"bytes,2,opt,name=account_uuid,json=accountUuid,proto3,oneof" json:"account_uuid,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticlesView) Reset() {
	*x = ArticlesView{}
	mi := &file_analytics_news_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticlesView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticlesView) ProtoMessage() {}

func (x *ArticlesView) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_news_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticlesView.ProtoReflect.Descriptor instead.
func (*ArticlesView) Descriptor() ([]byte, []int) {
	return file_analytics_news_proto_rawDescGZIP(), []int{3}
}

func (x *ArticlesView) GetArticleUuid() []byte {
	if x != nil {
		return x.ArticleUuid
	}
	return nil
}

func (x *ArticlesView) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *ArticlesView) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SetArticlesViewParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleUuids  [][]byte               `protobuf:"bytes,1,rep,name=article_uuids,json=articleUuids,proto3" json:"article_uuids,omitempty"`
	AccountUuid   []byte                 `protobuf:"bytes,2,opt,name=account_uuid,json=accountUuid,proto3,oneof" json:"account_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetArticlesViewParams) Reset() {
	*x = SetArticlesViewParams{}
	mi := &file_analytics_news_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArticlesViewParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArticlesViewParams) ProtoMessage() {}

func (x *SetArticlesViewParams) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_news_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetArticlesViewParams.ProtoReflect.Descriptor instead.
func (*SetArticlesViewParams) Descriptor() ([]byte, []int) {
	return file_analytics_news_proto_rawDescGZIP(), []int{4}
}

func (x *SetArticlesViewParams) GetArticleUuids() [][]byte {
	if x != nil {
		return x.ArticleUuids
	}
	return nil
}

func (x *SetArticlesViewParams) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

type SetArticleCommentParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleUuids  []byte                 `protobuf:"bytes,1,opt,name=article_uuids,json=articleUuids,proto3" json:"article_uuids,omitempty"`
	AccountUuid   []byte                 `protobuf:"bytes,2,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetArticleCommentParams) Reset() {
	*x = SetArticleCommentParams{}
	mi := &file_analytics_news_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetArticleCommentParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArticleCommentParams) ProtoMessage() {}

func (x *SetArticleCommentParams) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_news_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetArticleCommentParams.ProtoReflect.Descriptor instead.
func (*SetArticleCommentParams) Descriptor() ([]byte, []int) {
	return file_analytics_news_proto_rawDescGZIP(), []int{5}
}

func (x *SetArticleCommentParams) GetArticleUuids() []byte {
	if x != nil {
		return x.ArticleUuids
	}
	return nil
}

func (x *SetArticleCommentParams) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

type GetArticlesViewsByAccountParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   []byte                 `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	ListParams    *common.ListParams     `protobuf:"bytes,2,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesViewsByAccountParams) Reset() {
	*x = GetArticlesViewsByAccountParams{}
	mi := &file_analytics_news_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesViewsByAccountParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesViewsByAccountParams) ProtoMessage() {}

func (x *GetArticlesViewsByAccountParams) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_news_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesViewsByAccountParams.ProtoReflect.Descriptor instead.
func (*GetArticlesViewsByAccountParams) Descriptor() ([]byte, []int) {
	return file_analytics_news_proto_rawDescGZIP(), []int{6}
}

func (x *GetArticlesViewsByAccountParams) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *GetArticlesViewsByAccountParams) GetListParams() *common.ListParams {
	if x != nil {
		return x.ListParams
	}
	return nil
}

type GetArticlesViewsByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*ArticlesView        `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesViewsByAccountResponse) Reset() {
	*x = GetArticlesViewsByAccountResponse{}
	mi := &file_analytics_news_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesViewsByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesViewsByAccountResponse) ProtoMessage() {}

func (x *GetArticlesViewsByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_news_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesViewsByAccountResponse.ProtoReflect.Descriptor instead.
func (*GetArticlesViewsByAccountResponse) Descriptor() ([]byte, []int) {
	return file_analytics_news_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticlesViewsByAccountResponse) GetViews() []*ArticlesView {
	if x != nil {
		return x.Views
	}
	return nil
}

var File_analytics_news_proto protoreflect.FileDescriptor

var file_analytics_news_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2f, 0x6e, 0x65, 0x77, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x6e, 0x65, 0x77, 0x73, 0x2f, 0x6e, 0x65,
	0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x2b, 0x0a,
	0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6e, 0x65, 0x77, 0x73, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x3e, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x75, 0x69, 0x64, 0x73, 0x22, 0x4a, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x0c, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x56, 0x69, 0x65, 0x77, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x0f, 0x0a, 0x0d,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x22, 0x75, 0x0a,
	0x15, 0x53, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x56, 0x69, 0x65, 0x77,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x75, 0x69, 0x64, 0x73, 0x12, 0x26, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64,
	0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x55,
	0x75, 0x69, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x22, 0x79, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x56, 0x69, 0x65, 0x77, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x33, 0x0a,
	0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x22, 0x52, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x73, 0x56, 0x69, 0x65, 0x77, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x73, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x56, 0x69, 0x65, 0x77, 0x52,
	0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x33, 0x61, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74,
	0x69, 0x63, 0x73, 0x3b, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_analytics_news_proto_rawDescOnce sync.Once
	file_analytics_news_proto_rawDescData []byte
)

func file_analytics_news_proto_rawDescGZIP() []byte {
	file_analytics_news_proto_rawDescOnce.Do(func() {
		file_analytics_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_news_proto_rawDesc), len(file_analytics_news_proto_rawDesc)))
	})
	return file_analytics_news_proto_rawDescData
}

var file_analytics_news_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_analytics_news_proto_goTypes = []any{
	(*ArticlesCounts)(nil),                    // 0: analytics.ArticlesCounts
	(*GetArticlesCountsParams)(nil),           // 1: analytics.GetArticlesCountsParams
	(*GetArticlesCountsResponse)(nil),         // 2: analytics.GetArticlesCountsResponse
	(*ArticlesView)(nil),                      // 3: analytics.ArticlesView
	(*SetArticlesViewParams)(nil),             // 4: analytics.SetArticlesViewParams
	(*SetArticleCommentParams)(nil),           // 5: analytics.SetArticleCommentParams
	(*GetArticlesViewsByAccountParams)(nil),   // 6: analytics.GetArticlesViewsByAccountParams
	(*GetArticlesViewsByAccountResponse)(nil), // 7: analytics.GetArticlesViewsByAccountResponse
	(*news.ArticleCounts)(nil),                // 8: news.ArticleCounts
	(*timestamppb.Timestamp)(nil),             // 9: google.protobuf.Timestamp
	(*common.ListParams)(nil),                 // 10: common.ListParams
}
var file_analytics_news_proto_depIdxs = []int32{
	8,  // 0: analytics.ArticlesCounts.counts:type_name -> news.ArticleCounts
	0,  // 1: analytics.GetArticlesCountsResponse.list:type_name -> analytics.ArticlesCounts
	9,  // 2: analytics.ArticlesView.timestamp:type_name -> google.protobuf.Timestamp
	10, // 3: analytics.GetArticlesViewsByAccountParams.list_params:type_name -> common.ListParams
	3,  // 4: analytics.GetArticlesViewsByAccountResponse.views:type_name -> analytics.ArticlesView
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_analytics_news_proto_init() }
func file_analytics_news_proto_init() {
	if File_analytics_news_proto != nil {
		return
	}
	file_analytics_news_proto_msgTypes[3].OneofWrappers = []any{}
	file_analytics_news_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_news_proto_rawDesc), len(file_analytics_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analytics_news_proto_goTypes,
		DependencyIndexes: file_analytics_news_proto_depIdxs,
		MessageInfos:      file_analytics_news_proto_msgTypes,
	}.Build()
	File_analytics_news_proto = out.File
	file_analytics_news_proto_goTypes = nil
	file_analytics_news_proto_depIdxs = nil
}
