// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: accounts/subscribes.proto

package accountsv1

import (
	common "github.com/x3a-tech/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFollowingSourcesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *common.ListParams     `protobuf:"bytes,1,opt,name=listParams,proto3" json:"listParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingSourcesParams) Reset() {
	*x = GetFollowingSourcesParams{}
	mi := &file_accounts_subscribes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingSourcesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingSourcesParams) ProtoMessage() {}

func (x *GetFollowingSourcesParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingSourcesParams.ProtoReflect.Descriptor instead.
func (*GetFollowingSourcesParams) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{0}
}

func (x *GetFollowingSourcesParams) GetListParams() *common.ListParams {
	if x != nil {
		return x.ListParams
	}
	return nil
}

type GetFollowingSourcesParamsInner struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	AccountUuid   []byte                     `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *GetFollowingSourcesParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingSourcesParamsInner) Reset() {
	*x = GetFollowingSourcesParamsInner{}
	mi := &file_accounts_subscribes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingSourcesParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingSourcesParamsInner) ProtoMessage() {}

func (x *GetFollowingSourcesParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingSourcesParamsInner.ProtoReflect.Descriptor instead.
func (*GetFollowingSourcesParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowingSourcesParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *GetFollowingSourcesParamsInner) GetData() *GetFollowingSourcesParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFollowingSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUuids   [][]byte               `protobuf:"bytes,1,rep,name=source_uuids,json=sourceUuids,proto3" json:"source_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingSourcesResponse) Reset() {
	*x = GetFollowingSourcesResponse{}
	mi := &file_accounts_subscribes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingSourcesResponse) ProtoMessage() {}

func (x *GetFollowingSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingSourcesResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingSourcesResponse) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowingSourcesResponse) GetSourceUuids() [][]byte {
	if x != nil {
		return x.SourceUuids
	}
	return nil
}

type SubUnsubArticlesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleUuid   []byte                 `protobuf:"bytes,1,opt,name=article_uuid,json=articleUuid,proto3" json:"article_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubUnsubArticlesParams) Reset() {
	*x = SubUnsubArticlesParams{}
	mi := &file_accounts_subscribes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubUnsubArticlesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubUnsubArticlesParams) ProtoMessage() {}

func (x *SubUnsubArticlesParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubUnsubArticlesParams.ProtoReflect.Descriptor instead.
func (*SubUnsubArticlesParams) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{3}
}

func (x *SubUnsubArticlesParams) GetArticleUuid() []byte {
	if x != nil {
		return x.ArticleUuid
	}
	return nil
}

type FollowUnfollowSourceParamsInner struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AccountUuid   []byte                  `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *SubUnsubArticlesParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUnfollowSourceParamsInner) Reset() {
	*x = FollowUnfollowSourceParamsInner{}
	mi := &file_accounts_subscribes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUnfollowSourceParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUnfollowSourceParamsInner) ProtoMessage() {}

func (x *FollowUnfollowSourceParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUnfollowSourceParamsInner.ProtoReflect.Descriptor instead.
func (*FollowUnfollowSourceParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{4}
}

func (x *FollowUnfollowSourceParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *FollowUnfollowSourceParamsInner) GetData() *SubUnsubArticlesParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckSourcesFollowingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUuids   [][]byte               `protobuf:"bytes,1,rep,name=source_uuids,json=sourceUuids,proto3" json:"source_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSourcesFollowingParams) Reset() {
	*x = CheckSourcesFollowingParams{}
	mi := &file_accounts_subscribes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSourcesFollowingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSourcesFollowingParams) ProtoMessage() {}

func (x *CheckSourcesFollowingParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSourcesFollowingParams.ProtoReflect.Descriptor instead.
func (*CheckSourcesFollowingParams) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{5}
}

func (x *CheckSourcesFollowingParams) GetSourceUuids() [][]byte {
	if x != nil {
		return x.SourceUuids
	}
	return nil
}

type CheckSourcesFollowingParamsInner struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	AccountUuid   []byte                       `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *CheckSourcesFollowingParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSourcesFollowingParamsInner) Reset() {
	*x = CheckSourcesFollowingParamsInner{}
	mi := &file_accounts_subscribes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSourcesFollowingParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSourcesFollowingParamsInner) ProtoMessage() {}

func (x *CheckSourcesFollowingParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSourcesFollowingParamsInner.ProtoReflect.Descriptor instead.
func (*CheckSourcesFollowingParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{6}
}

func (x *CheckSourcesFollowingParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *CheckSourcesFollowingParamsInner) GetData() *CheckSourcesFollowingParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckSourcesFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []bool                 `protobuf:"varint,1,rep,packed,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSourcesFollowingResponse) Reset() {
	*x = CheckSourcesFollowingResponse{}
	mi := &file_accounts_subscribes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSourcesFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSourcesFollowingResponse) ProtoMessage() {}

func (x *CheckSourcesFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSourcesFollowingResponse.ProtoReflect.Descriptor instead.
func (*CheckSourcesFollowingResponse) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{7}
}

func (x *CheckSourcesFollowingResponse) GetChecks() []bool {
	if x != nil {
		return x.Checks
	}
	return nil
}

var File_accounts_subscribes_proto protoreflect.FileDescriptor

var file_accounts_subscribes_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52,
	0x0a, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x7c, 0x0a, 0x1e, 0x47,
	0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x73, 0x22, 0x3b, 0x0a, 0x16, 0x53,
	0x75, 0x62, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x55, 0x75, 0x69, 0x64, 0x22, 0x7a, 0x0a, 0x1f, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x55, 0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x34,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x55, 0x6e, 0x73, 0x75, 0x62,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x1b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x55, 0x75, 0x69, 0x64, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x20, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x39,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x1d, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x78, 0x33, 0x61, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x3b, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_accounts_subscribes_proto_rawDescOnce sync.Once
	file_accounts_subscribes_proto_rawDescData []byte
)

func file_accounts_subscribes_proto_rawDescGZIP() []byte {
	file_accounts_subscribes_proto_rawDescOnce.Do(func() {
		file_accounts_subscribes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_subscribes_proto_rawDesc), len(file_accounts_subscribes_proto_rawDesc)))
	})
	return file_accounts_subscribes_proto_rawDescData
}

var file_accounts_subscribes_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_accounts_subscribes_proto_goTypes = []any{
	(*GetFollowingSourcesParams)(nil),        // 0: accounts.GetFollowingSourcesParams
	(*GetFollowingSourcesParamsInner)(nil),   // 1: accounts.GetFollowingSourcesParamsInner
	(*GetFollowingSourcesResponse)(nil),      // 2: accounts.GetFollowingSourcesResponse
	(*SubUnsubArticlesParams)(nil),           // 3: accounts.SubUnsubArticlesParams
	(*FollowUnfollowSourceParamsInner)(nil),  // 4: accounts.FollowUnfollowSourceParamsInner
	(*CheckSourcesFollowingParams)(nil),      // 5: accounts.CheckSourcesFollowingParams
	(*CheckSourcesFollowingParamsInner)(nil), // 6: accounts.CheckSourcesFollowingParamsInner
	(*CheckSourcesFollowingResponse)(nil),    // 7: accounts.CheckSourcesFollowingResponse
	(*common.ListParams)(nil),                // 8: common.ListParams
}
var file_accounts_subscribes_proto_depIdxs = []int32{
	8, // 0: accounts.GetFollowingSourcesParams.listParams:type_name -> common.ListParams
	0, // 1: accounts.GetFollowingSourcesParamsInner.data:type_name -> accounts.GetFollowingSourcesParams
	3, // 2: accounts.FollowUnfollowSourceParamsInner.data:type_name -> accounts.SubUnsubArticlesParams
	5, // 3: accounts.CheckSourcesFollowingParamsInner.data:type_name -> accounts.CheckSourcesFollowingParams
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_accounts_subscribes_proto_init() }
func file_accounts_subscribes_proto_init() {
	if File_accounts_subscribes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_subscribes_proto_rawDesc), len(file_accounts_subscribes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accounts_subscribes_proto_goTypes,
		DependencyIndexes: file_accounts_subscribes_proto_depIdxs,
		MessageInfos:      file_accounts_subscribes_proto_msgTypes,
	}.Build()
	File_accounts_subscribes_proto = out.File
	file_accounts_subscribes_proto_goTypes = nil
	file_accounts_subscribes_proto_depIdxs = nil
}
