// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: accounts/subscribes.proto

package accountsv1

import (
	common "github.com/x3a-tech/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSubscribeArticlesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *common.ListParams     `protobuf:"bytes,1,opt,name=listParams,proto3" json:"listParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribeArticlesParams) Reset() {
	*x = GetSubscribeArticlesParams{}
	mi := &file_accounts_subscribes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribeArticlesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribeArticlesParams) ProtoMessage() {}

func (x *GetSubscribeArticlesParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribeArticlesParams.ProtoReflect.Descriptor instead.
func (*GetSubscribeArticlesParams) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubscribeArticlesParams) GetListParams() *common.ListParams {
	if x != nil {
		return x.ListParams
	}
	return nil
}

type GetSubscribeArticlesParamsInner struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	AccountUuid   []byte                      `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *GetSubscribeArticlesParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribeArticlesParamsInner) Reset() {
	*x = GetSubscribeArticlesParamsInner{}
	mi := &file_accounts_subscribes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribeArticlesParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribeArticlesParamsInner) ProtoMessage() {}

func (x *GetSubscribeArticlesParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribeArticlesParamsInner.ProtoReflect.Descriptor instead.
func (*GetSubscribeArticlesParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubscribeArticlesParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *GetSubscribeArticlesParamsInner) GetData() *GetSubscribeArticlesParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSubscribeArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleUuids  [][]byte               `protobuf:"bytes,1,rep,name=article_uuids,json=articleUuids,proto3" json:"article_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribeArticlesResponse) Reset() {
	*x = GetSubscribeArticlesResponse{}
	mi := &file_accounts_subscribes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribeArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribeArticlesResponse) ProtoMessage() {}

func (x *GetSubscribeArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribeArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetSubscribeArticlesResponse) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubscribeArticlesResponse) GetArticleUuids() [][]byte {
	if x != nil {
		return x.ArticleUuids
	}
	return nil
}

type SubUnsubArticlesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleUuid   []byte                 `protobuf:"bytes,1,opt,name=article_uuid,json=articleUuid,proto3" json:"article_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubUnsubArticlesParams) Reset() {
	*x = SubUnsubArticlesParams{}
	mi := &file_accounts_subscribes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubUnsubArticlesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubUnsubArticlesParams) ProtoMessage() {}

func (x *SubUnsubArticlesParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubUnsubArticlesParams.ProtoReflect.Descriptor instead.
func (*SubUnsubArticlesParams) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{3}
}

func (x *SubUnsubArticlesParams) GetArticleUuid() []byte {
	if x != nil {
		return x.ArticleUuid
	}
	return nil
}

type SubUnsubArticlesParamsInner struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AccountUuid   []byte                  `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *SubUnsubArticlesParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubUnsubArticlesParamsInner) Reset() {
	*x = SubUnsubArticlesParamsInner{}
	mi := &file_accounts_subscribes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubUnsubArticlesParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubUnsubArticlesParamsInner) ProtoMessage() {}

func (x *SubUnsubArticlesParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_subscribes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubUnsubArticlesParamsInner.ProtoReflect.Descriptor instead.
func (*SubUnsubArticlesParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_subscribes_proto_rawDescGZIP(), []int{4}
}

func (x *SubUnsubArticlesParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *SubUnsubArticlesParamsInner) GetData() *SubUnsubArticlesParams {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_accounts_subscribes_proto protoreflect.FileDescriptor

var file_accounts_subscribes_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x7e, 0x0a, 0x1f,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x1c,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x75, 0x69, 0x64,
	0x73, 0x22, 0x3b, 0x0a, 0x16, 0x53, 0x75, 0x62, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x75, 0x69, 0x64, 0x22, 0x76,
	0x0a, 0x1b, 0x53, 0x75, 0x62, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x55, 0x6e, 0x73,
	0x75, 0x62, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x33, 0x61, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x3b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_accounts_subscribes_proto_rawDescOnce sync.Once
	file_accounts_subscribes_proto_rawDescData []byte
)

func file_accounts_subscribes_proto_rawDescGZIP() []byte {
	file_accounts_subscribes_proto_rawDescOnce.Do(func() {
		file_accounts_subscribes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_subscribes_proto_rawDesc), len(file_accounts_subscribes_proto_rawDesc)))
	})
	return file_accounts_subscribes_proto_rawDescData
}

var file_accounts_subscribes_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_accounts_subscribes_proto_goTypes = []any{
	(*GetSubscribeArticlesParams)(nil),      // 0: accounts.GetSubscribeArticlesParams
	(*GetSubscribeArticlesParamsInner)(nil), // 1: accounts.GetSubscribeArticlesParamsInner
	(*GetSubscribeArticlesResponse)(nil),    // 2: accounts.GetSubscribeArticlesResponse
	(*SubUnsubArticlesParams)(nil),          // 3: accounts.SubUnsubArticlesParams
	(*SubUnsubArticlesParamsInner)(nil),     // 4: accounts.SubUnsubArticlesParamsInner
	(*common.ListParams)(nil),               // 5: common.ListParams
}
var file_accounts_subscribes_proto_depIdxs = []int32{
	5, // 0: accounts.GetSubscribeArticlesParams.listParams:type_name -> common.ListParams
	0, // 1: accounts.GetSubscribeArticlesParamsInner.data:type_name -> accounts.GetSubscribeArticlesParams
	3, // 2: accounts.SubUnsubArticlesParamsInner.data:type_name -> accounts.SubUnsubArticlesParams
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_accounts_subscribes_proto_init() }
func file_accounts_subscribes_proto_init() {
	if File_accounts_subscribes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_subscribes_proto_rawDesc), len(file_accounts_subscribes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accounts_subscribes_proto_goTypes,
		DependencyIndexes: file_accounts_subscribes_proto_depIdxs,
		MessageInfos:      file_accounts_subscribes_proto_msgTypes,
	}.Build()
	File_accounts_subscribes_proto = out.File
	file_accounts_subscribes_proto_goTypes = nil
	file_accounts_subscribes_proto_depIdxs = nil
}
