// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: accounts/widgets.proto

package accountsv1

import (
	common "github.com/x3a-tech/contract-go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidgetType int32

const (
	WidgetType_WIDGET_TYPE_UNSPECIFIED             WidgetType = 0
	WidgetType_WIDGET_TYPE_CUSTOM                  WidgetType = 1
	WidgetType_WIDGET_TYPE_PORTFOLIO_CRYPTO        WidgetType = 2
	WidgetType_WIDGET_TYPE_CURRENCIES_CRYPTO       WidgetType = 3
	WidgetType_WIDGET_TYPE_CURRENCIES_PAIRS        WidgetType = 4
	WidgetType_WIDGET_TYPE_CURRENCIES_STOCKS       WidgetType = 5
	WidgetType_WIDGET_TYPE_UNIVERSAL_CONVERTER     WidgetType = 6
	WidgetType_WIDGET_TYPE_MLM_CALC                WidgetType = 7
	WidgetType_WIDGET_TYPE_MINING_CALC             WidgetType = 8
	WidgetType_WIDGET_TYPE_NEWS_CATEGORIES         WidgetType = 9
	WidgetType_WIDGET_TYPE_NEWS_SOURCES            WidgetType = 10
	WidgetType_WIDGET_TYPE_NEWS_SOURCES_CATEGORIES WidgetType = 11
	WidgetType_WIDGET_TYPE_STATIC_DATA_LIST        WidgetType = 12
	WidgetType_WIDGET_TYPE_STATIC_DATA_ENTITY      WidgetType = 13
)

// Enum value maps for WidgetType.
var (
	WidgetType_name = map[int32]string{
		0:  "WIDGET_TYPE_UNSPECIFIED",
		1:  "WIDGET_TYPE_CUSTOM",
		2:  "WIDGET_TYPE_PORTFOLIO_CRYPTO",
		3:  "WIDGET_TYPE_CURRENCIES_CRYPTO",
		4:  "WIDGET_TYPE_CURRENCIES_PAIRS",
		5:  "WIDGET_TYPE_CURRENCIES_STOCKS",
		6:  "WIDGET_TYPE_UNIVERSAL_CONVERTER",
		7:  "WIDGET_TYPE_MLM_CALC",
		8:  "WIDGET_TYPE_MINING_CALC",
		9:  "WIDGET_TYPE_NEWS_CATEGORIES",
		10: "WIDGET_TYPE_NEWS_SOURCES",
		11: "WIDGET_TYPE_NEWS_SOURCES_CATEGORIES",
		12: "WIDGET_TYPE_STATIC_DATA_LIST",
		13: "WIDGET_TYPE_STATIC_DATA_ENTITY",
	}
	WidgetType_value = map[string]int32{
		"WIDGET_TYPE_UNSPECIFIED":             0,
		"WIDGET_TYPE_CUSTOM":                  1,
		"WIDGET_TYPE_PORTFOLIO_CRYPTO":        2,
		"WIDGET_TYPE_CURRENCIES_CRYPTO":       3,
		"WIDGET_TYPE_CURRENCIES_PAIRS":        4,
		"WIDGET_TYPE_CURRENCIES_STOCKS":       5,
		"WIDGET_TYPE_UNIVERSAL_CONVERTER":     6,
		"WIDGET_TYPE_MLM_CALC":                7,
		"WIDGET_TYPE_MINING_CALC":             8,
		"WIDGET_TYPE_NEWS_CATEGORIES":         9,
		"WIDGET_TYPE_NEWS_SOURCES":            10,
		"WIDGET_TYPE_NEWS_SOURCES_CATEGORIES": 11,
		"WIDGET_TYPE_STATIC_DATA_LIST":        12,
		"WIDGET_TYPE_STATIC_DATA_ENTITY":      13,
	}
)

func (x WidgetType) Enum() *WidgetType {
	p := new(WidgetType)
	*p = x
	return p
}

func (x WidgetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WidgetType) Descriptor() protoreflect.EnumDescriptor {
	return file_accounts_widgets_proto_enumTypes[0].Descriptor()
}

func (WidgetType) Type() protoreflect.EnumType {
	return &file_accounts_widgets_proto_enumTypes[0]
}

func (x WidgetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WidgetType.Descriptor instead.
func (WidgetType) EnumDescriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{0}
}

type WidgetUcType int32

const (
	WidgetUcType_WIDGET_UC_UNSPECIFIED WidgetUcType = 0
	WidgetUcType_WIDGET_UC_CRYPTO      WidgetUcType = 1
	WidgetUcType_WIDGET_UC_FIAT        WidgetUcType = 2
)

// Enum value maps for WidgetUcType.
var (
	WidgetUcType_name = map[int32]string{
		0: "WIDGET_UC_UNSPECIFIED",
		1: "WIDGET_UC_CRYPTO",
		2: "WIDGET_UC_FIAT",
	}
	WidgetUcType_value = map[string]int32{
		"WIDGET_UC_UNSPECIFIED": 0,
		"WIDGET_UC_CRYPTO":      1,
		"WIDGET_UC_FIAT":        2,
	}
)

func (x WidgetUcType) Enum() *WidgetUcType {
	p := new(WidgetUcType)
	*p = x
	return p
}

func (x WidgetUcType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WidgetUcType) Descriptor() protoreflect.EnumDescriptor {
	return file_accounts_widgets_proto_enumTypes[1].Descriptor()
}

func (WidgetUcType) Type() protoreflect.EnumType {
	return &file_accounts_widgets_proto_enumTypes[1]
}

func (x WidgetUcType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WidgetUcType.Descriptor instead.
func (WidgetUcType) EnumDescriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{1}
}

type Widget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          WidgetType             `protobuf:"varint,3,opt,name=type,proto3,enum=accounts.WidgetType" json:"type,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Pc            *WidgetListPc          `protobuf:"bytes,6,opt,name=pc,proto3,oneof" json:"pc,omitempty"`
	Cc            *WidgetListCurrencies  `protobuf:"bytes,7,opt,name=cc,proto3,oneof" json:"cc,omitempty"`
	Uc            *WidgetListUc          `protobuf:"bytes,8,opt,name=uc,proto3,oneof" json:"uc,omitempty"`
	Nc            *WidgetListNc          `protobuf:"bytes,9,opt,name=nc,proto3,oneof" json:"nc,omitempty"`
	Ns            *WidgetListNs          `protobuf:"bytes,10,opt,name=ns,proto3,oneof" json:"ns,omitempty"`
	Nsc           *WidgetListNsc         `protobuf:"bytes,11,opt,name=nsc,proto3,oneof" json:"nsc,omitempty"`
	SdList        *int32                 `protobuf:"varint,12,opt,name=sd_list,json=sdList,proto3,oneof" json:"sd_list,omitempty"`
	SdEntity      *int32                 `protobuf:"varint,13,opt,name=sd_entity,json=sdEntity,proto3,oneof" json:"sd_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_accounts_widgets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{0}
}

func (x *Widget) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Widget) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Widget) GetType() WidgetType {
	if x != nil {
		return x.Type
	}
	return WidgetType_WIDGET_TYPE_UNSPECIFIED
}

func (x *Widget) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Widget) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Widget) GetPc() *WidgetListPc {
	if x != nil {
		return x.Pc
	}
	return nil
}

func (x *Widget) GetCc() *WidgetListCurrencies {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Widget) GetUc() *WidgetListUc {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *Widget) GetNc() *WidgetListNc {
	if x != nil {
		return x.Nc
	}
	return nil
}

func (x *Widget) GetNs() *WidgetListNs {
	if x != nil {
		return x.Ns
	}
	return nil
}

func (x *Widget) GetNsc() *WidgetListNsc {
	if x != nil {
		return x.Nsc
	}
	return nil
}

func (x *Widget) GetSdList() int32 {
	if x != nil && x.SdList != nil {
		return *x.SdList
	}
	return 0
}

func (x *Widget) GetSdEntity() int32 {
	if x != nil && x.SdEntity != nil {
		return *x.SdEntity
	}
	return 0
}

type WidgetListPc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*WidgetPc            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetListPc) Reset() {
	*x = WidgetListPc{}
	mi := &file_accounts_widgets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetListPc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetListPc) ProtoMessage() {}

func (x *WidgetListPc) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetListPc.ProtoReflect.Descriptor instead.
func (*WidgetListPc) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{1}
}

func (x *WidgetListPc) GetList() []*WidgetPc {
	if x != nil {
		return x.List
	}
	return nil
}

type WidgetListCurrencies struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []int32                `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetListCurrencies) Reset() {
	*x = WidgetListCurrencies{}
	mi := &file_accounts_widgets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetListCurrencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetListCurrencies) ProtoMessage() {}

func (x *WidgetListCurrencies) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetListCurrencies.ProtoReflect.Descriptor instead.
func (*WidgetListCurrencies) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{2}
}

func (x *WidgetListCurrencies) GetList() []int32 {
	if x != nil {
		return x.List
	}
	return nil
}

type WidgetListUc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*WidgetUcValue       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetListUc) Reset() {
	*x = WidgetListUc{}
	mi := &file_accounts_widgets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetListUc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetListUc) ProtoMessage() {}

func (x *WidgetListUc) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetListUc.ProtoReflect.Descriptor instead.
func (*WidgetListUc) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{3}
}

func (x *WidgetListUc) GetList() []*WidgetUcValue {
	if x != nil {
		return x.List
	}
	return nil
}

type WidgetListNc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []int32                `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetListNc) Reset() {
	*x = WidgetListNc{}
	mi := &file_accounts_widgets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetListNc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetListNc) ProtoMessage() {}

func (x *WidgetListNc) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetListNc.ProtoReflect.Descriptor instead.
func (*WidgetListNc) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{4}
}

func (x *WidgetListNc) GetList() []int32 {
	if x != nil {
		return x.List
	}
	return nil
}

type WidgetListNs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          [][]byte               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetListNs) Reset() {
	*x = WidgetListNs{}
	mi := &file_accounts_widgets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetListNs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetListNs) ProtoMessage() {}

func (x *WidgetListNs) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetListNs.ProtoReflect.Descriptor instead.
func (*WidgetListNs) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{5}
}

func (x *WidgetListNs) GetList() [][]byte {
	if x != nil {
		return x.List
	}
	return nil
}

type WidgetListNsc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*WidgetNscValue      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetListNsc) Reset() {
	*x = WidgetListNsc{}
	mi := &file_accounts_widgets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetListNsc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetListNsc) ProtoMessage() {}

func (x *WidgetListNsc) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetListNsc.ProtoReflect.Descriptor instead.
func (*WidgetListNsc) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{6}
}

func (x *WidgetListNsc) GetList() []*WidgetNscValue {
	if x != nil {
		return x.List
	}
	return nil
}

type GetWidgetsParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *common.ListParams     `protobuf:"bytes,2,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetsParams) Reset() {
	*x = GetWidgetsParams{}
	mi := &file_accounts_widgets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetsParams) ProtoMessage() {}

func (x *GetWidgetsParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetsParams.ProtoReflect.Descriptor instead.
func (*GetWidgetsParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{7}
}

func (x *GetWidgetsParams) GetListParams() *common.ListParams {
	if x != nil {
		return x.ListParams
	}
	return nil
}

type GetWidgetsParamsInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   []byte                 `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *GetWidgetsParams      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetsParamsInner) Reset() {
	*x = GetWidgetsParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetsParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetsParamsInner) ProtoMessage() {}

func (x *GetWidgetsParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetsParamsInner.ProtoReflect.Descriptor instead.
func (*GetWidgetsParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{8}
}

func (x *GetWidgetsParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *GetWidgetsParamsInner) GetData() *GetWidgetsParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetWidgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widgets       []*Widget              `protobuf:"bytes,1,rep,name=widgets,proto3" json:"widgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetsResponse) Reset() {
	*x = GetWidgetsResponse{}
	mi := &file_accounts_widgets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetsResponse) ProtoMessage() {}

func (x *GetWidgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetsResponse.ProtoReflect.Descriptor instead.
func (*GetWidgetsResponse) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{9}
}

func (x *GetWidgetsResponse) GetWidgets() []*Widget {
	if x != nil {
		return x.Widgets
	}
	return nil
}

type CreateWidgetParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type          WidgetType             `protobuf:"varint,2,opt,name=type,proto3,enum=accounts.WidgetType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWidgetParams) Reset() {
	*x = CreateWidgetParams{}
	mi := &file_accounts_widgets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWidgetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWidgetParams) ProtoMessage() {}

func (x *CreateWidgetParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWidgetParams.ProtoReflect.Descriptor instead.
func (*CreateWidgetParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{10}
}

func (x *CreateWidgetParams) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWidgetParams) GetType() WidgetType {
	if x != nil {
		return x.Type
	}
	return WidgetType_WIDGET_TYPE_UNSPECIFIED
}

type CreateWidgetParamsInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   []byte                 `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *CreateWidgetParams    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWidgetParamsInner) Reset() {
	*x = CreateWidgetParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWidgetParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWidgetParamsInner) ProtoMessage() {}

func (x *CreateWidgetParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWidgetParamsInner.ProtoReflect.Descriptor instead.
func (*CreateWidgetParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{11}
}

func (x *CreateWidgetParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *CreateWidgetParamsInner) GetData() *CreateWidgetParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateWidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widget        *Widget                `protobuf:"bytes,1,opt,name=widget,proto3" json:"widget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWidgetResponse) Reset() {
	*x = CreateWidgetResponse{}
	mi := &file_accounts_widgets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWidgetResponse) ProtoMessage() {}

func (x *CreateWidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWidgetResponse.ProtoReflect.Descriptor instead.
func (*CreateWidgetResponse) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{12}
}

func (x *CreateWidgetResponse) GetWidget() *Widget {
	if x != nil {
		return x.Widget
	}
	return nil
}

type DeleteWidgetParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   []byte                 `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	WidgetUuid    []byte                 `protobuf:"bytes,2,opt,name=widget_uuid,json=widgetUuid,proto3" json:"widget_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWidgetParams) Reset() {
	*x = DeleteWidgetParams{}
	mi := &file_accounts_widgets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWidgetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWidgetParams) ProtoMessage() {}

func (x *DeleteWidgetParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWidgetParams.ProtoReflect.Descriptor instead.
func (*DeleteWidgetParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteWidgetParams) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *DeleteWidgetParams) GetWidgetUuid() []byte {
	if x != nil {
		return x.WidgetUuid
	}
	return nil
}

type WidgetPc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetPc) Reset() {
	*x = WidgetPc{}
	mi := &file_accounts_widgets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetPc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetPc) ProtoMessage() {}

func (x *WidgetPc) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetPc.ProtoReflect.Descriptor instead.
func (*WidgetPc) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{14}
}

func (x *WidgetPc) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WidgetPc) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateWidgetPcParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetUuid    []byte                 `protobuf:"bytes,1,opt,name=widget_uuid,json=widgetUuid,proto3" json:"widget_uuid,omitempty"`
	UpsertValues  []*WidgetPc            `protobuf:"bytes,2,rep,name=upsert_values,json=upsertValues,proto3" json:"upsert_values,omitempty"`
	RemoveValues  []int32                `protobuf:"varint,3,rep,packed,name=remove_values,json=removeValues,proto3" json:"remove_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetPcParams) Reset() {
	*x = UpdateWidgetPcParams{}
	mi := &file_accounts_widgets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetPcParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetPcParams) ProtoMessage() {}

func (x *UpdateWidgetPcParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetPcParams.ProtoReflect.Descriptor instead.
func (*UpdateWidgetPcParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateWidgetPcParams) GetWidgetUuid() []byte {
	if x != nil {
		return x.WidgetUuid
	}
	return nil
}

func (x *UpdateWidgetPcParams) GetUpsertValues() []*WidgetPc {
	if x != nil {
		return x.UpsertValues
	}
	return nil
}

func (x *UpdateWidgetPcParams) GetRemoveValues() []int32 {
	if x != nil {
		return x.RemoveValues
	}
	return nil
}

type UpdateWidgetPcParamsInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   []byte                 `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *UpdateWidgetPcParams  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetPcParamsInner) Reset() {
	*x = UpdateWidgetPcParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetPcParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetPcParamsInner) ProtoMessage() {}

func (x *UpdateWidgetPcParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetPcParamsInner.ProtoReflect.Descriptor instead.
func (*UpdateWidgetPcParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateWidgetPcParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *UpdateWidgetPcParamsInner) GetData() *UpdateWidgetPcParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type SortWidgetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sort          int32                  `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortWidgetValue) Reset() {
	*x = SortWidgetValue{}
	mi := &file_accounts_widgets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortWidgetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortWidgetValue) ProtoMessage() {}

func (x *SortWidgetValue) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortWidgetValue.ProtoReflect.Descriptor instead.
func (*SortWidgetValue) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{17}
}

func (x *SortWidgetValue) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SortWidgetValue) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type SortWidgetValuesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetUuid    []byte                 `protobuf:"bytes,1,opt,name=widget_uuid,json=widgetUuid,proto3" json:"widget_uuid,omitempty"`
	Sort          []*SortWidgetValue     `protobuf:"bytes,2,rep,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortWidgetValuesParams) Reset() {
	*x = SortWidgetValuesParams{}
	mi := &file_accounts_widgets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortWidgetValuesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortWidgetValuesParams) ProtoMessage() {}

func (x *SortWidgetValuesParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortWidgetValuesParams.ProtoReflect.Descriptor instead.
func (*SortWidgetValuesParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{18}
}

func (x *SortWidgetValuesParams) GetWidgetUuid() []byte {
	if x != nil {
		return x.WidgetUuid
	}
	return nil
}

func (x *SortWidgetValuesParams) GetSort() []*SortWidgetValue {
	if x != nil {
		return x.Sort
	}
	return nil
}

type SortWidgetValuesParamsInner struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AccountUuid   []byte                  `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *SortWidgetValuesParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortWidgetValuesParamsInner) Reset() {
	*x = SortWidgetValuesParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortWidgetValuesParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortWidgetValuesParamsInner) ProtoMessage() {}

func (x *SortWidgetValuesParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortWidgetValuesParamsInner.ProtoReflect.Descriptor instead.
func (*SortWidgetValuesParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{19}
}

func (x *SortWidgetValuesParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *SortWidgetValuesParamsInner) GetData() *SortWidgetValuesParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateWidgetSingleValuesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetUuid    []byte                 `protobuf:"bytes,1,opt,name=widget_uuid,json=widgetUuid,proto3" json:"widget_uuid,omitempty"`
	AddValues     []int32                `protobuf:"varint,2,rep,packed,name=add_values,json=addValues,proto3" json:"add_values,omitempty"`
	RemoveValues  []int32                `protobuf:"varint,3,rep,packed,name=remove_values,json=removeValues,proto3" json:"remove_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetSingleValuesParams) Reset() {
	*x = UpdateWidgetSingleValuesParams{}
	mi := &file_accounts_widgets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetSingleValuesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetSingleValuesParams) ProtoMessage() {}

func (x *UpdateWidgetSingleValuesParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetSingleValuesParams.ProtoReflect.Descriptor instead.
func (*UpdateWidgetSingleValuesParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateWidgetSingleValuesParams) GetWidgetUuid() []byte {
	if x != nil {
		return x.WidgetUuid
	}
	return nil
}

func (x *UpdateWidgetSingleValuesParams) GetAddValues() []int32 {
	if x != nil {
		return x.AddValues
	}
	return nil
}

func (x *UpdateWidgetSingleValuesParams) GetRemoveValues() []int32 {
	if x != nil {
		return x.RemoveValues
	}
	return nil
}

type UpdateWidgetSingleValuesParamsInner struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	AccountUuid   []byte                          `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *UpdateWidgetSingleValuesParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetSingleValuesParamsInner) Reset() {
	*x = UpdateWidgetSingleValuesParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetSingleValuesParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetSingleValuesParamsInner) ProtoMessage() {}

func (x *UpdateWidgetSingleValuesParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetSingleValuesParamsInner.ProtoReflect.Descriptor instead.
func (*UpdateWidgetSingleValuesParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateWidgetSingleValuesParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *UpdateWidgetSingleValuesParamsInner) GetData() *UpdateWidgetSingleValuesParams {
	if x != nil {
		return x.Data
	}
	return nil
}

// News Sources
type UpdateWidgetSingleValuesUuidParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetUuid    []byte                 `protobuf:"bytes,1,opt,name=widget_uuid,json=widgetUuid,proto3" json:"widget_uuid,omitempty"`
	AddValues     [][]byte               `protobuf:"bytes,2,rep,name=add_values,json=addValues,proto3" json:"add_values,omitempty"`
	RemoveValues  [][]byte               `protobuf:"bytes,3,rep,name=remove_values,json=removeValues,proto3" json:"remove_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetSingleValuesUuidParams) Reset() {
	*x = UpdateWidgetSingleValuesUuidParams{}
	mi := &file_accounts_widgets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetSingleValuesUuidParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetSingleValuesUuidParams) ProtoMessage() {}

func (x *UpdateWidgetSingleValuesUuidParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetSingleValuesUuidParams.ProtoReflect.Descriptor instead.
func (*UpdateWidgetSingleValuesUuidParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateWidgetSingleValuesUuidParams) GetWidgetUuid() []byte {
	if x != nil {
		return x.WidgetUuid
	}
	return nil
}

func (x *UpdateWidgetSingleValuesUuidParams) GetAddValues() [][]byte {
	if x != nil {
		return x.AddValues
	}
	return nil
}

func (x *UpdateWidgetSingleValuesUuidParams) GetRemoveValues() [][]byte {
	if x != nil {
		return x.RemoveValues
	}
	return nil
}

type UpdateWidgetSingleValuesUuidParamsInner struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	AccountUuid   []byte                              `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *UpdateWidgetSingleValuesUuidParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetSingleValuesUuidParamsInner) Reset() {
	*x = UpdateWidgetSingleValuesUuidParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetSingleValuesUuidParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetSingleValuesUuidParamsInner) ProtoMessage() {}

func (x *UpdateWidgetSingleValuesUuidParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetSingleValuesUuidParamsInner.ProtoReflect.Descriptor instead.
func (*UpdateWidgetSingleValuesUuidParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateWidgetSingleValuesUuidParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *UpdateWidgetSingleValuesUuidParamsInner) GetData() *UpdateWidgetSingleValuesUuidParams {
	if x != nil {
		return x.Data
	}
	return nil
}

type WidgetUcValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          WidgetUcType           `protobuf:"varint,2,opt,name=type,proto3,enum=accounts.WidgetUcType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetUcValue) Reset() {
	*x = WidgetUcValue{}
	mi := &file_accounts_widgets_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetUcValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetUcValue) ProtoMessage() {}

func (x *WidgetUcValue) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetUcValue.ProtoReflect.Descriptor instead.
func (*WidgetUcValue) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{24}
}

func (x *WidgetUcValue) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WidgetUcValue) GetType() WidgetUcType {
	if x != nil {
		return x.Type
	}
	return WidgetUcType_WIDGET_UC_UNSPECIFIED
}

type UpdateWidgetUcParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetUuid    []byte                 `protobuf:"bytes,1,opt,name=widget_uuid,json=widgetUuid,proto3" json:"widget_uuid,omitempty"`
	UpsertValues  []*WidgetUcValue       `protobuf:"bytes,2,rep,name=upsert_values,json=upsertValues,proto3" json:"upsert_values,omitempty"`
	RemoveValues  []int32                `protobuf:"varint,3,rep,packed,name=remove_values,json=removeValues,proto3" json:"remove_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetUcParams) Reset() {
	*x = UpdateWidgetUcParams{}
	mi := &file_accounts_widgets_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetUcParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetUcParams) ProtoMessage() {}

func (x *UpdateWidgetUcParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetUcParams.ProtoReflect.Descriptor instead.
func (*UpdateWidgetUcParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateWidgetUcParams) GetWidgetUuid() []byte {
	if x != nil {
		return x.WidgetUuid
	}
	return nil
}

func (x *UpdateWidgetUcParams) GetUpsertValues() []*WidgetUcValue {
	if x != nil {
		return x.UpsertValues
	}
	return nil
}

func (x *UpdateWidgetUcParams) GetRemoveValues() []int32 {
	if x != nil {
		return x.RemoveValues
	}
	return nil
}

type UpdateWidgetUcParamsInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   []byte                 `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *UpdateWidgetUcParams  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetUcParamsInner) Reset() {
	*x = UpdateWidgetUcParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetUcParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetUcParamsInner) ProtoMessage() {}

func (x *UpdateWidgetUcParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetUcParamsInner.ProtoReflect.Descriptor instead.
func (*UpdateWidgetUcParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateWidgetUcParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *UpdateWidgetUcParamsInner) GetData() *UpdateWidgetUcParams {
	if x != nil {
		return x.Data
	}
	return nil
}

// News Source Categories
type WidgetNscValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUuid    []byte                 `protobuf:"bytes,1,opt,name=source_uuid,json=sourceUuid,proto3" json:"source_uuid,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetNscValue) Reset() {
	*x = WidgetNscValue{}
	mi := &file_accounts_widgets_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetNscValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetNscValue) ProtoMessage() {}

func (x *WidgetNscValue) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetNscValue.ProtoReflect.Descriptor instead.
func (*WidgetNscValue) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{27}
}

func (x *WidgetNscValue) GetSourceUuid() []byte {
	if x != nil {
		return x.SourceUuid
	}
	return nil
}

func (x *WidgetNscValue) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type UpdateWidgetNscParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetUuid    []byte                 `protobuf:"bytes,1,opt,name=widget_uuid,json=widgetUuid,proto3" json:"widget_uuid,omitempty"`
	UpsertValues  []*WidgetNscValue      `protobuf:"bytes,2,rep,name=upsert_values,json=upsertValues,proto3" json:"upsert_values,omitempty"`
	RemoveValues  []int32                `protobuf:"varint,3,rep,packed,name=remove_values,json=removeValues,proto3" json:"remove_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetNscParams) Reset() {
	*x = UpdateWidgetNscParams{}
	mi := &file_accounts_widgets_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetNscParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetNscParams) ProtoMessage() {}

func (x *UpdateWidgetNscParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetNscParams.ProtoReflect.Descriptor instead.
func (*UpdateWidgetNscParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateWidgetNscParams) GetWidgetUuid() []byte {
	if x != nil {
		return x.WidgetUuid
	}
	return nil
}

func (x *UpdateWidgetNscParams) GetUpsertValues() []*WidgetNscValue {
	if x != nil {
		return x.UpsertValues
	}
	return nil
}

func (x *UpdateWidgetNscParams) GetRemoveValues() []int32 {
	if x != nil {
		return x.RemoveValues
	}
	return nil
}

type UpdateWidgetNscParamsInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   []byte                 `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *UpdateWidgetNscParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetNscParamsInner) Reset() {
	*x = UpdateWidgetNscParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetNscParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetNscParamsInner) ProtoMessage() {}

func (x *UpdateWidgetNscParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetNscParamsInner.ProtoReflect.Descriptor instead.
func (*UpdateWidgetNscParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateWidgetNscParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *UpdateWidgetNscParamsInner) GetData() *UpdateWidgetNscParams {
	if x != nil {
		return x.Data
	}
	return nil
}

// Static Data List & Entity
type UpdateWidgetSingleParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetUuid    []byte                 `protobuf:"bytes,1,opt,name=widget_uuid,json=widgetUuid,proto3" json:"widget_uuid,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetSingleParams) Reset() {
	*x = UpdateWidgetSingleParams{}
	mi := &file_accounts_widgets_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetSingleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetSingleParams) ProtoMessage() {}

func (x *UpdateWidgetSingleParams) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetSingleParams.ProtoReflect.Descriptor instead.
func (*UpdateWidgetSingleParams) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateWidgetSingleParams) GetWidgetUuid() []byte {
	if x != nil {
		return x.WidgetUuid
	}
	return nil
}

func (x *UpdateWidgetSingleParams) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateWidgetSingleParamsInner struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	AccountUuid   []byte                    `protobuf:"bytes,1,opt,name=account_uuid,json=accountUuid,proto3" json:"account_uuid,omitempty"`
	Data          *UpdateWidgetSingleParams `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWidgetSingleParamsInner) Reset() {
	*x = UpdateWidgetSingleParamsInner{}
	mi := &file_accounts_widgets_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWidgetSingleParamsInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWidgetSingleParamsInner) ProtoMessage() {}

func (x *UpdateWidgetSingleParamsInner) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_widgets_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWidgetSingleParamsInner.ProtoReflect.Descriptor instead.
func (*UpdateWidgetSingleParamsInner) Descriptor() ([]byte, []int) {
	return file_accounts_widgets_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateWidgetSingleParamsInner) GetAccountUuid() []byte {
	if x != nil {
		return x.AccountUuid
	}
	return nil
}

func (x *UpdateWidgetSingleParamsInner) GetData() *UpdateWidgetSingleParams {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_accounts_widgets_proto protoreflect.FileDescriptor

var file_accounts_widgets_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2f, 0x77, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcb, 0x04, 0x0a, 0x06, 0x57, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2b, 0x0a, 0x02, 0x70, 0x63, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x63, 0x48, 0x00, 0x52, 0x02,
	0x70, 0x63, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65,
	0x73, 0x48, 0x01, 0x52, 0x02, 0x63, 0x63, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x02, 0x75, 0x63,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x63, 0x48, 0x02,
	0x52, 0x02, 0x75, 0x63, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x02, 0x6e, 0x63, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x63, 0x48, 0x03, 0x52, 0x02, 0x6e,
	0x63, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x02, 0x6e, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x73, 0x48, 0x04, 0x52, 0x02, 0x6e, 0x73, 0x88, 0x01,
	0x01, 0x12, 0x2e, 0x0a, 0x03, 0x6e, 0x73, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x4e, 0x73, 0x63, 0x48, 0x05, 0x52, 0x03, 0x6e, 0x73, 0x63, 0x88, 0x01,
	0x01, 0x12, 0x1c, 0x0a, 0x07, 0x73, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x06, 0x52, 0x06, 0x73, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x20, 0x0a, 0x09, 0x73, 0x64, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x07, 0x52, 0x08, 0x73, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x88, 0x01,
	0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x70, 0x63, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x63, 0x63, 0x42,
	0x05, 0x0a, 0x03, 0x5f, 0x75, 0x63, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x6e, 0x63, 0x42, 0x05, 0x0a,
	0x03, 0x5f, 0x6e, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6e, 0x73, 0x63, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x73, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x64, 0x5f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x36, 0x0a, 0x0c, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x63, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x50, 0x63, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x2a,
	0x0a, 0x14, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x0c, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x63, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x63, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x57,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x3d, 0x0a, 0x0d, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x73, 0x63,
	0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x4e, 0x73, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x47,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x33, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0a, 0x6c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x6a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x52, 0x07, 0x77, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x73, 0x22, 0x54, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x6e, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x52, 0x06, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x22, 0x58, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x55, 0x75, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x08, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x50, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x14, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x50, 0x63, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0d, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x50, 0x63, 0x52, 0x0c,
	0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x22, 0x72, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x50, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x50, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x0f, 0x53, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x68, 0x0a, 0x16,
	0x53, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2e, 0x53, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x76, 0x0a, 0x1b, 0x53, 0x6f, 0x72, 0x74, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x85,
	0x01, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x61, 0x64, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x23, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x89, 0x01, 0x0a, 0x22, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x55, 0x75, 0x69, 0x64,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x64, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x27,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x55, 0x75, 0x69, 0x64, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x40, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x55, 0x75, 0x69, 0x64,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x0d,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x63, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x14, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x63, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x3c, 0x0a, 0x0d, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x63, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x0c, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x63, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x0e, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x4e, 0x73, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x9c,
	0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4e,
	0x73, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x77,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x0d, 0x75, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x4e, 0x73, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x75, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x74, 0x0a,
	0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x4e, 0x73, 0x63,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x33,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x4e, 0x73, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7a, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x2a, 0xd5, 0x03, 0x0a, 0x0a, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1b, 0x0a, 0x17, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16,
	0x0a, 0x12, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x55,
	0x53, 0x54, 0x4f, 0x4d, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x4f, 0x52, 0x54, 0x46, 0x4f, 0x4c, 0x49, 0x4f, 0x5f,
	0x43, 0x52, 0x59, 0x50, 0x54, 0x4f, 0x10, 0x02, 0x12, 0x21, 0x0a, 0x1d, 0x57, 0x49, 0x44, 0x47,
	0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x43, 0x49,
	0x45, 0x53, 0x5f, 0x43, 0x52, 0x59, 0x50, 0x54, 0x4f, 0x10, 0x03, 0x12, 0x20, 0x0a, 0x1c, 0x57,
	0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x55, 0x52, 0x52, 0x45,
	0x4e, 0x43, 0x49, 0x45, 0x53, 0x5f, 0x50, 0x41, 0x49, 0x52, 0x53, 0x10, 0x04, 0x12, 0x21, 0x0a,
	0x1d, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x55, 0x52,
	0x52, 0x45, 0x4e, 0x43, 0x49, 0x45, 0x53, 0x5f, 0x53, 0x54, 0x4f, 0x43, 0x4b, 0x53, 0x10, 0x05,
	0x12, 0x23, 0x0a, 0x1f, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x49, 0x56, 0x45, 0x52, 0x53, 0x41, 0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52,
	0x54, 0x45, 0x52, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x4c, 0x4d, 0x5f, 0x43, 0x41, 0x4c, 0x43, 0x10, 0x07, 0x12,
	0x1b, 0x0a, 0x17, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d,
	0x49, 0x4e, 0x49, 0x4e, 0x47, 0x5f, 0x43, 0x41, 0x4c, 0x43, 0x10, 0x08, 0x12, 0x1f, 0x0a, 0x1b,
	0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x45, 0x57, 0x53,
	0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x49, 0x45, 0x53, 0x10, 0x09, 0x12, 0x1c, 0x0a,
	0x18, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x45, 0x57,
	0x53, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x53, 0x10, 0x0a, 0x12, 0x27, 0x0a, 0x23, 0x57,
	0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x45, 0x57, 0x53, 0x5f,
	0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x53, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x49,
	0x45, 0x53, 0x10, 0x0b, 0x12, 0x20, 0x0a, 0x1c, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x43, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f,
	0x4c, 0x49, 0x53, 0x54, 0x10, 0x0c, 0x12, 0x22, 0x0a, 0x1e, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x43, 0x5f, 0x44, 0x41, 0x54,
	0x41, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x10, 0x0d, 0x2a, 0x53, 0x0a, 0x0c, 0x57, 0x69,
	0x64, 0x67, 0x65, 0x74, 0x55, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x57, 0x49,
	0x44, 0x47, 0x45, 0x54, 0x5f, 0x55, 0x43, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x57, 0x49, 0x44, 0x47, 0x45, 0x54, 0x5f,
	0x55, 0x43, 0x5f, 0x43, 0x52, 0x59, 0x50, 0x54, 0x4f, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x57,
	0x49, 0x44, 0x47, 0x45, 0x54, 0x5f, 0x55, 0x43, 0x5f, 0x46, 0x49, 0x41, 0x54, 0x10, 0x02, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x33,
	0x61, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2d,
	0x67, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x3b, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_accounts_widgets_proto_rawDescOnce sync.Once
	file_accounts_widgets_proto_rawDescData []byte
)

func file_accounts_widgets_proto_rawDescGZIP() []byte {
	file_accounts_widgets_proto_rawDescOnce.Do(func() {
		file_accounts_widgets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_widgets_proto_rawDesc), len(file_accounts_widgets_proto_rawDesc)))
	})
	return file_accounts_widgets_proto_rawDescData
}

var file_accounts_widgets_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_accounts_widgets_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_accounts_widgets_proto_goTypes = []any{
	(WidgetType)(0),                                 // 0: accounts.WidgetType
	(WidgetUcType)(0),                               // 1: accounts.WidgetUcType
	(*Widget)(nil),                                  // 2: accounts.Widget
	(*WidgetListPc)(nil),                            // 3: accounts.WidgetListPc
	(*WidgetListCurrencies)(nil),                    // 4: accounts.WidgetListCurrencies
	(*WidgetListUc)(nil),                            // 5: accounts.WidgetListUc
	(*WidgetListNc)(nil),                            // 6: accounts.WidgetListNc
	(*WidgetListNs)(nil),                            // 7: accounts.WidgetListNs
	(*WidgetListNsc)(nil),                           // 8: accounts.WidgetListNsc
	(*GetWidgetsParams)(nil),                        // 9: accounts.GetWidgetsParams
	(*GetWidgetsParamsInner)(nil),                   // 10: accounts.GetWidgetsParamsInner
	(*GetWidgetsResponse)(nil),                      // 11: accounts.GetWidgetsResponse
	(*CreateWidgetParams)(nil),                      // 12: accounts.CreateWidgetParams
	(*CreateWidgetParamsInner)(nil),                 // 13: accounts.CreateWidgetParamsInner
	(*CreateWidgetResponse)(nil),                    // 14: accounts.CreateWidgetResponse
	(*DeleteWidgetParams)(nil),                      // 15: accounts.DeleteWidgetParams
	(*WidgetPc)(nil),                                // 16: accounts.WidgetPc
	(*UpdateWidgetPcParams)(nil),                    // 17: accounts.UpdateWidgetPcParams
	(*UpdateWidgetPcParamsInner)(nil),               // 18: accounts.UpdateWidgetPcParamsInner
	(*SortWidgetValue)(nil),                         // 19: accounts.SortWidgetValue
	(*SortWidgetValuesParams)(nil),                  // 20: accounts.SortWidgetValuesParams
	(*SortWidgetValuesParamsInner)(nil),             // 21: accounts.SortWidgetValuesParamsInner
	(*UpdateWidgetSingleValuesParams)(nil),          // 22: accounts.UpdateWidgetSingleValuesParams
	(*UpdateWidgetSingleValuesParamsInner)(nil),     // 23: accounts.UpdateWidgetSingleValuesParamsInner
	(*UpdateWidgetSingleValuesUuidParams)(nil),      // 24: accounts.UpdateWidgetSingleValuesUuidParams
	(*UpdateWidgetSingleValuesUuidParamsInner)(nil), // 25: accounts.UpdateWidgetSingleValuesUuidParamsInner
	(*WidgetUcValue)(nil),                           // 26: accounts.WidgetUcValue
	(*UpdateWidgetUcParams)(nil),                    // 27: accounts.UpdateWidgetUcParams
	(*UpdateWidgetUcParamsInner)(nil),               // 28: accounts.UpdateWidgetUcParamsInner
	(*WidgetNscValue)(nil),                          // 29: accounts.WidgetNscValue
	(*UpdateWidgetNscParams)(nil),                   // 30: accounts.UpdateWidgetNscParams
	(*UpdateWidgetNscParamsInner)(nil),              // 31: accounts.UpdateWidgetNscParamsInner
	(*UpdateWidgetSingleParams)(nil),                // 32: accounts.UpdateWidgetSingleParams
	(*UpdateWidgetSingleParamsInner)(nil),           // 33: accounts.UpdateWidgetSingleParamsInner
	(*timestamppb.Timestamp)(nil),                   // 34: google.protobuf.Timestamp
	(*common.ListParams)(nil),                       // 35: common.ListParams
}
var file_accounts_widgets_proto_depIdxs = []int32{
	0,  // 0: accounts.Widget.type:type_name -> accounts.WidgetType
	34, // 1: accounts.Widget.created_at:type_name -> google.protobuf.Timestamp
	3,  // 2: accounts.Widget.pc:type_name -> accounts.WidgetListPc
	4,  // 3: accounts.Widget.cc:type_name -> accounts.WidgetListCurrencies
	5,  // 4: accounts.Widget.uc:type_name -> accounts.WidgetListUc
	6,  // 5: accounts.Widget.nc:type_name -> accounts.WidgetListNc
	7,  // 6: accounts.Widget.ns:type_name -> accounts.WidgetListNs
	8,  // 7: accounts.Widget.nsc:type_name -> accounts.WidgetListNsc
	16, // 8: accounts.WidgetListPc.list:type_name -> accounts.WidgetPc
	26, // 9: accounts.WidgetListUc.list:type_name -> accounts.WidgetUcValue
	29, // 10: accounts.WidgetListNsc.list:type_name -> accounts.WidgetNscValue
	35, // 11: accounts.GetWidgetsParams.list_params:type_name -> common.ListParams
	9,  // 12: accounts.GetWidgetsParamsInner.data:type_name -> accounts.GetWidgetsParams
	2,  // 13: accounts.GetWidgetsResponse.widgets:type_name -> accounts.Widget
	0,  // 14: accounts.CreateWidgetParams.type:type_name -> accounts.WidgetType
	12, // 15: accounts.CreateWidgetParamsInner.data:type_name -> accounts.CreateWidgetParams
	2,  // 16: accounts.CreateWidgetResponse.widget:type_name -> accounts.Widget
	16, // 17: accounts.UpdateWidgetPcParams.upsert_values:type_name -> accounts.WidgetPc
	17, // 18: accounts.UpdateWidgetPcParamsInner.data:type_name -> accounts.UpdateWidgetPcParams
	19, // 19: accounts.SortWidgetValuesParams.sort:type_name -> accounts.SortWidgetValue
	20, // 20: accounts.SortWidgetValuesParamsInner.data:type_name -> accounts.SortWidgetValuesParams
	22, // 21: accounts.UpdateWidgetSingleValuesParamsInner.data:type_name -> accounts.UpdateWidgetSingleValuesParams
	24, // 22: accounts.UpdateWidgetSingleValuesUuidParamsInner.data:type_name -> accounts.UpdateWidgetSingleValuesUuidParams
	1,  // 23: accounts.WidgetUcValue.type:type_name -> accounts.WidgetUcType
	26, // 24: accounts.UpdateWidgetUcParams.upsert_values:type_name -> accounts.WidgetUcValue
	27, // 25: accounts.UpdateWidgetUcParamsInner.data:type_name -> accounts.UpdateWidgetUcParams
	29, // 26: accounts.UpdateWidgetNscParams.upsert_values:type_name -> accounts.WidgetNscValue
	30, // 27: accounts.UpdateWidgetNscParamsInner.data:type_name -> accounts.UpdateWidgetNscParams
	32, // 28: accounts.UpdateWidgetSingleParamsInner.data:type_name -> accounts.UpdateWidgetSingleParams
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_accounts_widgets_proto_init() }
func file_accounts_widgets_proto_init() {
	if File_accounts_widgets_proto != nil {
		return
	}
	file_accounts_widgets_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_widgets_proto_rawDesc), len(file_accounts_widgets_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accounts_widgets_proto_goTypes,
		DependencyIndexes: file_accounts_widgets_proto_depIdxs,
		EnumInfos:         file_accounts_widgets_proto_enumTypes,
		MessageInfos:      file_accounts_widgets_proto_msgTypes,
	}.Build()
	File_accounts_widgets_proto = out.File
	file_accounts_widgets_proto_goTypes = nil
	file_accounts_widgets_proto_depIdxs = nil
}
