// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: sd/group-keys.proto

package sdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupKey) Reset() {
	*x = GroupKey{}
	mi := &file_sd_group_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupKey) ProtoMessage() {}

func (x *GroupKey) ProtoReflect() protoreflect.Message {
	mi := &file_sd_group_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupKey.ProtoReflect.Descriptor instead.
func (*GroupKey) Descriptor() ([]byte, []int) {
	return file_sd_group_keys_proto_rawDescGZIP(), []int{0}
}

func (x *GroupKey) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GroupKey) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type NewGroupKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGroupKey) Reset() {
	*x = NewGroupKey{}
	mi := &file_sd_group_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGroupKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGroupKey) ProtoMessage() {}

func (x *NewGroupKey) ProtoReflect() protoreflect.Message {
	mi := &file_sd_group_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGroupKey.ProtoReflect.Descriptor instead.
func (*NewGroupKey) Descriptor() ([]byte, []int) {
	return file_sd_group_keys_proto_rawDescGZIP(), []int{1}
}

func (x *NewGroupKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NewGroupKey) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_sd_group_keys_proto protoreflect.FileDescriptor

var file_sd_group_keys_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x73, 0x64, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x6b, 0x65, 0x79, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x73, 0x64, 0x22, 0x42, 0x0a, 0x08, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x35, 0x0a,
	0x0b, 0x4e, 0x65, 0x77, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x78, 0x33, 0x61, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x64, 0x3b, 0x73, 0x64, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sd_group_keys_proto_rawDescOnce sync.Once
	file_sd_group_keys_proto_rawDescData []byte
)

func file_sd_group_keys_proto_rawDescGZIP() []byte {
	file_sd_group_keys_proto_rawDescOnce.Do(func() {
		file_sd_group_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sd_group_keys_proto_rawDesc), len(file_sd_group_keys_proto_rawDesc)))
	})
	return file_sd_group_keys_proto_rawDescData
}

var file_sd_group_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sd_group_keys_proto_goTypes = []any{
	(*GroupKey)(nil),    // 0: sd.GroupKey
	(*NewGroupKey)(nil), // 1: sd.NewGroupKey
}
var file_sd_group_keys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sd_group_keys_proto_init() }
func file_sd_group_keys_proto_init() {
	if File_sd_group_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sd_group_keys_proto_rawDesc), len(file_sd_group_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sd_group_keys_proto_goTypes,
		DependencyIndexes: file_sd_group_keys_proto_depIdxs,
		MessageInfos:      file_sd_group_keys_proto_msgTypes,
	}.Build()
	File_sd_group_keys_proto = out.File
	file_sd_group_keys_proto_goTypes = nil
	file_sd_group_keys_proto_depIdxs = nil
}
