// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: sd/l10n.proto

package sdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L10NAttr int32

const (
	L10NAttr_L10N_ATTR_UNDEFINED L10NAttr = 0
	L10NAttr_NAME                L10NAttr = 1
	L10NAttr_DESCRIPTION         L10NAttr = 2
	L10NAttr_CONTENT             L10NAttr = 3
	L10NAttr_PLACEHOLDER         L10NAttr = 4
	L10NAttr_POSTFIX             L10NAttr = 5
	L10NAttr_PREFIX              L10NAttr = 6
)

// Enum value maps for L10NAttr.
var (
	L10NAttr_name = map[int32]string{
		0: "L10N_ATTR_UNDEFINED",
		1: "NAME",
		2: "DESCRIPTION",
		3: "CONTENT",
		4: "PLACEHOLDER",
		5: "POSTFIX",
		6: "PREFIX",
	}
	L10NAttr_value = map[string]int32{
		"L10N_ATTR_UNDEFINED": 0,
		"NAME":                1,
		"DESCRIPTION":         2,
		"CONTENT":             3,
		"PLACEHOLDER":         4,
		"POSTFIX":             5,
		"PREFIX":              6,
	}
)

func (x L10NAttr) Enum() *L10NAttr {
	p := new(L10NAttr)
	*p = x
	return p
}

func (x L10NAttr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L10NAttr) Descriptor() protoreflect.EnumDescriptor {
	return file_sd_l10n_proto_enumTypes[0].Descriptor()
}

func (L10NAttr) Type() protoreflect.EnumType {
	return &file_sd_l10n_proto_enumTypes[0]
}

func (x L10NAttr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L10NAttr.Descriptor instead.
func (L10NAttr) EnumDescriptor() ([]byte, []int) {
	return file_sd_l10n_proto_rawDescGZIP(), []int{0}
}

type L10N struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attr          L10NAttr               `protobuf:"varint,1,opt,name=attr,proto3,enum=sd.L10NAttr" json:"attr,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L10N) Reset() {
	*x = L10N{}
	mi := &file_sd_l10n_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L10N) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L10N) ProtoMessage() {}

func (x *L10N) ProtoReflect() protoreflect.Message {
	mi := &file_sd_l10n_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L10N.ProtoReflect.Descriptor instead.
func (*L10N) Descriptor() ([]byte, []int) {
	return file_sd_l10n_proto_rawDescGZIP(), []int{0}
}

func (x *L10N) GetAttr() L10NAttr {
	if x != nil {
		return x.Attr
	}
	return L10NAttr_L10N_ATTR_UNDEFINED
}

func (x *L10N) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_sd_l10n_proto protoreflect.FileDescriptor

var file_sd_l10n_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x73, 0x64, 0x2f, 0x6c, 0x31, 0x30, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x73, 0x64, 0x22, 0x3c, 0x0a, 0x04, 0x4c, 0x31, 0x30, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x61,
	0x74, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x64, 0x2e, 0x4c,
	0x31, 0x30, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x2a, 0x75, 0x0a, 0x08, 0x4c, 0x31, 0x30, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x12, 0x17, 0x0a,
	0x13, 0x4c, 0x31, 0x30, 0x4e, 0x5f, 0x41, 0x54, 0x54, 0x52, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46,
	0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x01,
	0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x45, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x0f,
	0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x53, 0x54, 0x46, 0x49, 0x58, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06,
	0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10, 0x06, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x33, 0x61, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x64, 0x3b, 0x73,
	0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sd_l10n_proto_rawDescOnce sync.Once
	file_sd_l10n_proto_rawDescData []byte
)

func file_sd_l10n_proto_rawDescGZIP() []byte {
	file_sd_l10n_proto_rawDescOnce.Do(func() {
		file_sd_l10n_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sd_l10n_proto_rawDesc), len(file_sd_l10n_proto_rawDesc)))
	})
	return file_sd_l10n_proto_rawDescData
}

var file_sd_l10n_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sd_l10n_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sd_l10n_proto_goTypes = []any{
	(L10NAttr)(0), // 0: sd.L10nAttr
	(*L10N)(nil),  // 1: sd.L10n
}
var file_sd_l10n_proto_depIdxs = []int32{
	0, // 0: sd.L10n.attr:type_name -> sd.L10nAttr
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sd_l10n_proto_init() }
func file_sd_l10n_proto_init() {
	if File_sd_l10n_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sd_l10n_proto_rawDesc), len(file_sd_l10n_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sd_l10n_proto_goTypes,
		DependencyIndexes: file_sd_l10n_proto_depIdxs,
		EnumInfos:         file_sd_l10n_proto_enumTypes,
		MessageInfos:      file_sd_l10n_proto_msgTypes,
	}.Build()
	File_sd_l10n_proto = out.File
	file_sd_l10n_proto_goTypes = nil
	file_sd_l10n_proto_depIdxs = nil
}
