// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: ws/subjects.proto

package wsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subject int32

const (
	Subject_SUBJECT_UNSPECIFIED Subject = 0
	Subject_GLOBAL              Subject = 1
	Subject_NOTIFICATION        Subject = 2
	Subject_ARTICLE_COMMENTS    Subject = 3
	Subject_ENTITY_REVIEWS      Subject = 4
	Subject_CRYPTO_COINS        Subject = 5
	Subject_STOCKS_ELEMENT      Subject = 6
	Subject_FOREX_PAIRS         Subject = 7
)

// Enum value maps for Subject.
var (
	Subject_name = map[int32]string{
		0: "SUBJECT_UNSPECIFIED",
		1: "GLOBAL",
		2: "NOTIFICATION",
		3: "ARTICLE_COMMENTS",
		4: "ENTITY_REVIEWS",
		5: "CRYPTO_COINS",
		6: "STOCKS_ELEMENT",
		7: "FOREX_PAIRS",
	}
	Subject_value = map[string]int32{
		"SUBJECT_UNSPECIFIED": 0,
		"GLOBAL":              1,
		"NOTIFICATION":        2,
		"ARTICLE_COMMENTS":    3,
		"ENTITY_REVIEWS":      4,
		"CRYPTO_COINS":        5,
		"STOCKS_ELEMENT":      6,
		"FOREX_PAIRS":         7,
	}
)

func (x Subject) Enum() *Subject {
	p := new(Subject)
	*p = x
	return p
}

func (x Subject) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Subject) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_subjects_proto_enumTypes[0].Descriptor()
}

func (Subject) Type() protoreflect.EnumType {
	return &file_ws_subjects_proto_enumTypes[0]
}

func (x Subject) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Subject.Descriptor instead.
func (Subject) EnumDescriptor() ([]byte, []int) {
	return file_ws_subjects_proto_rawDescGZIP(), []int{0}
}

var File_ws_subjects_proto protoreflect.FileDescriptor

var file_ws_subjects_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x77, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x77, 0x73, 0x2a, 0xa1, 0x01, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x55, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x47, 0x4c, 0x4f, 0x42, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x49,
	0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x52,
	0x54, 0x49, 0x43, 0x4c, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x53, 0x10, 0x03,
	0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f, 0x52, 0x45, 0x56, 0x49, 0x45,
	0x57, 0x53, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x52, 0x59, 0x50, 0x54, 0x4f, 0x5f, 0x43,
	0x4f, 0x49, 0x4e, 0x53, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x4f, 0x43, 0x4b, 0x53,
	0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x4f,
	0x52, 0x45, 0x58, 0x5f, 0x50, 0x41, 0x49, 0x52, 0x53, 0x10, 0x07, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x33, 0x61, 0x2d, 0x74, 0x65,
	0x63, 0x68, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x77,
	0x73, 0x3b, 0x77, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_ws_subjects_proto_rawDescOnce sync.Once
	file_ws_subjects_proto_rawDescData []byte
)

func file_ws_subjects_proto_rawDescGZIP() []byte {
	file_ws_subjects_proto_rawDescOnce.Do(func() {
		file_ws_subjects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_subjects_proto_rawDesc), len(file_ws_subjects_proto_rawDesc)))
	})
	return file_ws_subjects_proto_rawDescData
}

var file_ws_subjects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ws_subjects_proto_goTypes = []any{
	(Subject)(0), // 0: ws.Subject
}
var file_ws_subjects_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ws_subjects_proto_init() }
func file_ws_subjects_proto_init() {
	if File_ws_subjects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_subjects_proto_rawDesc), len(file_ws_subjects_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_subjects_proto_goTypes,
		DependencyIndexes: file_ws_subjects_proto_depIdxs,
		EnumInfos:         file_ws_subjects_proto_enumTypes,
	}.Build()
	File_ws_subjects_proto = out.File
	file_ws_subjects_proto_goTypes = nil
	file_ws_subjects_proto_depIdxs = nil
}
